<?php
namespace DHP_FW;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-30 at 13:35:10.
 */
class ErrorHandlerTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var ErrorHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ErrorHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * I found no other way to test the exceptions as it would seem
     * that PHPUnit eats them and we are unable to catch them and
     * verify that the method has been registered as an exception handler
     * 
     */
    public function testExceptionHandler() {
        $this->expectOutputString('Uncaught exception'."\n".
                                    'E_UNKNOWN : \'Test triggered exception\'');
        $e =  new \ErrorException('Test triggered exception',666);
        $this->object->exceptionHandler($e);
    }

    /**
     * @expectedException \ErrorException
     */
    public function testErrorHandler() {
        trigger_error('A php error triggered');
    }
}
